schema:
  - './schema.graphql'
documents:
  - '**/*.{ts,tsx}'
extensions:
  codegen:
    overwrites: true
    generates:
      ./src/generated/:
        preset: '@soundxyz/codegen-fragments'
        config:
          enumsAsConst: true

